# Generated by Django 5.0.6 on 2024-07-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startcourse',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
